### ISSUE TITLE
Add Media Keys support

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [jsakamoto/Toolbelt.Blazor.HotKeys#9]
Please add support for media keys. Also maybe you should check for new javascript event "code" and not use "keyCode".

Sample for media key support:
`function playPauseKb(event) {
  var x = event.code;
  var y = audio.paused;
  //debug
  console.log(x);

  //p on the keyboard
  if (x === "MediaPlayPause" && y == 1) {

    alert("playing");

  } else if (x === "MediaPlayPause") {

    alert("paused");

  }
}
`

**Comment by jsakamoto** [comment]
@NeoCoderMatrix86  Thank you for good proposal!

I'll add support for media keys, and also improve the JavaScript code of this library.

(Probably I can release the new version in a week, I think.)

**Comment by NeoCoderMatrix86** [comment]
Thank you :). Please do not forget media keys like "Next", "Previous", etc.

**Comment by jsakamoto** [comment]
I released a new version of this library.

- https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys/10.0.0

This version allows you to register some media keys such as play/pause, next and prev track as hotkeys.

If you need to hook any keys that are not covered by `Keys` enum values, you can use the new overload version of the `HotKeyContext.Add()` methods that are accepted "key name" as a string.

Please remember that the "key name" is a bit different from the "key" and "code" properties of the DOM event object.
The "key name" comes from "key" and "code", but it is tried to converting to one of the Keys enum values names.
if the keyboard event is not covered by Keys enum values, the "key name" will be the value of "code" or "key".

If you have to reference the native "key" and "code" property values, you can use the `HotKeys.OnKeyDown` event for this purpose.
The `HotKeys.OnKeyDown` event is not so convenient rather than `HotKeysContext.Add()`, but the event argument object of this event exposes the native "key" and "code" property values of the HTML keyboard event object.

Please try it out. :)

**Comment by NeoCoderMatrix86** [comment]
Thanks for this release :). I will test it the next days, currently I'm working on other issues and need some time. I will inform you, when I tried it :).

**Comment by NeoCoderMatrix86** [comment]
I get an exception when upgrading the nuget package without changes to the code. When I enter a key in my form, this exception occurs: 
`Uncaught Error: System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 3.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.Converters.StringConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, String& value)
   at System.Text.Json.Serialization.JsonConverter`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadValueCore[Object](JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments(JSRuntime jsRuntime, String methodIdentifier, String arguments, Type[] parameterTypes)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
    call_method https://localhost:44359/_framework/dotnet.5.0.2.js:1
    bind_static_method https://localhost:44359/_framework/dotnet.5.0.2.js:1
    invokeDotNetFromJS https://localhost:44359/_framework/blazor.webassembly.js:1
    p https://localhost:44359/_framework/blazor.webassembly.js:1
    invokeMethod https://localhost:44359/_framework/blazor.webassembly.js:1
    h https://localhost:44359/_content/Toolbelt.Blazor.HotKeys/script.min.js:1`

**Comment by jsakamoto** [comment]
@NeoCoderMatrix86 

It looks like something that is the problem related to the web browser's cache, I think.
I want to improve this point, but anyway, the workaround at this time is, "hard refresh (a.k.a. super reload)".

Could you try to follow the instruction as below?
1. Open your web app by the web browser.
2. Enter Ctrl+Shift+I to open the developer tools of the web browser.
3. Set focus to browser's document content, and enter Ctrl+Shift+R to hard refresh.

**Comment by NeoCoderMatrix86** [comment]
I tried already resetting browser cache. Since I use edge for development, I used:

1. Ctrl + Shift + F5 to reload the hole page.

I also tried it in a private tab in firefox, this also has thrown the exception above. Using the shortcuts you provided didn't change anything (no reload, no refresh). If I use the previous release (9.0.1) it works like charm. What browser do you use?

**Comment by jsakamoto** [comment]
> What browser do you use?

I tested this library by following browsers on Windows 10 20H2 x64:

- Microsoft Edge v.88.0.705.56 (64bit)
- Mozilla Firefox 85.0 (64bit)
- Google Chrome  88.0.4324.146 (64bit)

I used https://jsakamoto.github.io/Toolbelt.Blazor.HotKeys/ to do the test.

I'll investigate deeply the error message that you provided, and I'll try to resolve this issue.

And, could you try to https://jsakamoto.github.io/Toolbelt.Blazor.HotKeys/  and could you report to me that works fine on your browser or not?

**Comment by NeoCoderMatrix86** [comment]
Perfect :). I tried your test page (https://jsakamoto.github.io/Toolbelt.Blazor.HotKeys/) and it works like charm. So I think it is some kind of update problem. Do I have to register other javascript or startup services?

**Comment by jsakamoto** [comment]
> Do I have to register other javascript or startup services? 

No, you do not have to do it. 

Maybe just I'm overlooking something like a bug in an edge case, I think.

I'm still investigating the error message you provided.

While I'm doing that, if you prefer, you can clone this repository and add this library's project as a project reference to your project instead of the NuGet package reference, and run your project under the debugger to figure out this issue.

Of cause, this is just one of the ideas of me.
I'll continue resolving this issue.

**Comment by jsakamoto** [comment]
After my investigation, the cache still seems to be the cause for me.

Could you attach the `https://localhost:44359/_content/Toolbelt.Blazor.HotKeys/script.min.js` file that was downloaded from your app in development?

Or, instead of attaching the .js file, could you compare it to "https://github.com/jsakamoto/Toolbelt.Blazor.HotKeys/blob/master/Toolbelt.Blazor.HotKeys/wwwroot/script.min.js" by your self?

**Comment by NeoCoderMatrix86** [comment]
I just did the update again and now it works perfectly. I also compared both javascript files, they are identical. Maybe it was a really bad bug with caching, but now it works. I will now test implementing the media keys and then use the new version :). Thanks for your work 👍 :)!

**Comment by jsakamoto** [comment]
More details:

Fact 1. The error message represents that the C# side expected a string value as an argument, but the JavaScript side provided a number value.
Fact 2. The error occurred when invoking the "OnKyDown" C# method from the JavaScript code.
Fact 3. In the updating to ver.10 of this library, the "OnKyDown" C# method signature was also changed. The type of 2nd argument is changed from number (`Keys` enum type) to string.

From these facts, it seems to the old JavaScript code calls the newer version C# code, I think.

**Comment by jsakamoto** [comment]
@NeoCoderMatrix86 
Oh, thanks reporting!

I'm happy you resolved this issue!

**Comment by NeoCoderMatrix86** [comment]
Works perfect, thanks for the good implementation and fast reply :).

**Comment by jsakamoto** [comment]
_**Aside:**_ I'm trying to resolve the "cache" problem.

- https://github.com/jsakamoto/Toolbelt.Blazor.HotKeys/commit/b981549b0f2c518ebef63ee3f8803017a9b6534a#diff-9633cff56f14a1054c928b137fe88c3566492503baaa1eb1b3e97693ac01c6b1R47

I'll release the new version In a few days.
